add container and iac test

diff --git a/.github/workflows/snyk-code-manual.yml b/.github/workflows/snyk-code-manual.yml
--- a/.github/workflows/snyk-code-manual.yml
+++ b/.github/workflows/snyk-code-manual.yml
@@ -19,6 +19,13 @@ jobs:
         continue-on-error: true
         env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+        run: |
+          docker build . -t goof_test:latest
+          snyk container monitor goof_test:latest --file=Dockerfile
+      - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+        run: |
+          snyk iac test || true
       - name: Upload SARIF
         uses: github/codeql-action/upload-sarif@v2
         with:
